"""Extract and execute Stable's actual SHA-0 and PACK writer functions.
Requires Python 3 and a C compiler (clang on Windows, cc on Unix).
Generated files are test fixtures, not an app native dependency.
"""
from pathlib import Path
import json
import os
import shutil
import subprocess
import tempfile

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "SoftEtherVPN_Stable/src"

def function(source, signature):
    start = source.index(signature)
    brace = source.index("{", start)
    depth = 1
    end = brace + 1
    while depth:
        depth += (source[end] == "{") - (source[end] == "}")
        end += 1
    return source[start:end]

encrypt = (SRC / "Mayaqua/Encrypt.c").read_text(encoding="utf-8-sig")
sha = encrypt[encrypt.index("#define rol(bits,"):encrypt.index("int GetSslClientCertIndex()")]
memory = (SRC / "Mayaqua/Memory.c").read_text(encoding="utf-8-sig")
pack = (SRC / "Mayaqua/Pack.c").read_text(encoding="utf-8-sig")
stub = r'''
#include <stdint.h>
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <wchar.h>
typedef uint32_t UINT; typedef uint64_t UINT64; typedef unsigned char UCHAR;
typedef unsigned char BYTE; typedef int bool;
#define true 1
#define false 0
#define VALUE_INT 0
#define VALUE_DATA 1
#define VALUE_STR 2
#define VALUE_UNISTR 3
#define VALUE_INT64 4
typedef struct { unsigned char bytes[4096]; UINT size; } BUF;
typedef struct { UINT Size, IntValue; void *Data; char *Str; wchar_t *UniStr; UINT64 Int64Value; } VALUE;
typedef struct { char name[64]; UINT num_value, type; VALUE **values; } ELEMENT;
UINT Endian32(UINT x) { return ((x>>24)&255)|((x>>8)&65280)|((x<<8)&16711680)|(x<<24); }
UINT64 Endian64(UINT64 x) { return ((UINT64)Endian32((UINT)x)<<32)|Endian32((UINT)(x>>32)); }
void WriteBuf(BUF *b, void *p, UINT n) { if(n>sizeof(b->bytes)-b->size) abort(); memcpy(b->bytes+b->size,p,n); b->size+=n; }
UINT StrLen(char *p) { return (UINT)strlen(p); }
UINT CalcUniToUtf8(wchar_t *p) { (void)p; abort(); }
void *ZeroMalloc(UINT n) { return calloc(1,n); }
void Free(void *p) { free(p); }
void UniToUtf8(BYTE *p, UINT n, wchar_t *u) { (void)p;(void)n;(void)u;abort(); }
'''
pieces = [function(memory, "bool WriteBufInt(BUF *b, UINT value)"),
          function(memory, "bool WriteBufInt64(BUF *b, UINT64 value)"),
          function(memory, "bool WriteBufStr(BUF *b, char *str)"),
          function(pack, "void WriteValue(BUF *b, VALUE *v, UINT type)"),
          function(pack, "void WriteElement(BUF *b, ELEMENT *e)")]
main = r'''
void printhex(const char *name, const unsigned char *data, size_t n) {
    printf("%s=",name); for(size_t i=0;i<n;i++) printf("%02x",data[i]); puts("");
}
int main(void) {
    unsigned char input[130],digest[20],random[20],hash[20],both[40];
    int sizes[]={0,3,55,56,57,63,64,65,119,120,128};
    for(int i=0;i<130;i++) input[i]=(unsigned char)i;
    for(int i=0;i<11;i++) { char name[40]; sprintf(name,"sha0_%d",sizes[i]); MY_SHA0_hash(input,sizes[i],digest); printhex(name,digest,20); }
    MY_SHA0_hash("passwordUSER",12,hash);
    for(int i=0;i<20;i++) random[i]=(unsigned char)i;
    memcpy(both,hash,20);memcpy(both+20,random,20);MY_SHA0_hash(both,40,digest);
    printhex("password_challenge",digest,20);
    BUF b={0}; VALUE v={0}; VALUE *vals[]={&v}; ELEMENT e={"x",1,VALUE_INT,vals};
    v.IntValue=0x01020304; WriteBufInt(&b,1);WriteElement(&b,&e);printhex("pack_integer",b.bytes,b.size);
    b.size=0;strcpy(e.name,"method");e.type=VALUE_STR;v.Str="login";WriteBufInt(&b,1);WriteElement(&b,&e);printhex("pack_string",b.bytes,b.size);
    b.size=0;strcpy(e.name,"secure_password");e.type=VALUE_DATA;v.Data=digest;v.Size=20;WriteBufInt(&b,1);WriteElement(&b,&e);printhex("pack_data",b.bytes,b.size);
    b.size=0;strcpy(e.name,"wide");e.type=VALUE_INT64;v.Int64Value=0x0102030405060708ULL;WriteBufInt(&b,1);WriteElement(&b,&e);printhex("pack_int64",b.bytes,b.size);
    return 0;
}
'''
compiler = shutil.which("clang") or shutil.which("cc")
if not compiler:
    raise SystemExit("C compiler required")
build = ROOT / "tools/.vectors-build"
build.mkdir(exist_ok=True)
c = build / "vectors.c"
c.write_text(stub + sha + "\n".join(pieces) + main, encoding="utf-8")
exe = build / ("vectors.exe" if os.name == "nt" else "vectors")
subprocess.run([compiler, "-O2", str(c), "-o", str(exe)], check=True)
output = subprocess.check_output([str(exe)], text=True)
dest = ROOT / "core-protocol/src/test/resources/upstream-vectors.properties"
dest.parent.mkdir(parents=True, exist_ok=True)
dest.write_text("# Generated by executing actual pinned Stable C functions\n" + output, encoding="ascii")
print(f"Wrote {len(output.splitlines())} upstream C vectors to {dest}")
